---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: docker.io/envoyproxy/envoy:v1.21.1
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.21.1
          url: docker.io/envoyproxy/envoy:v1.21.1
  image: index.docker.io/envoyproxy/envoy@sha256:e9ad4cde73ffb01402c4e3fb6ce1a764d9e84650230135b88495f30904a378fc
- annotations:
    kbld.carvel.dev/id: ghcr.io/projectcontour/contour:v1.20.1
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.20.1
          url: ghcr.io/projectcontour/contour:v1.20.1
      - preresolved:
          url: ghcr.io/projectcontour/contour@sha256:1f428f7eae35de450c3873902e67349526a55689101f68cc7b06a0ffb0853f51
      - preresolved:
          url: ghcr.io/projectcontour/contour@sha256:1f428f7eae35de450c3873902e67349526a55689101f68cc7b06a0ffb0853f51
  image: ghcr.io/projectcontour/contour@sha256:1f428f7eae35de450c3873902e67349526a55689101f68cc7b06a0ffb0853f51
kind: ImagesLock
